### ISSUE TITLE
program template has a bug for location

### ISSUE THREAD

**Issue by kmccurley** [kaymckelly/freelance-iacr#115]
In the template for the program, the location doesn't show up in track 0 because the template refers to the location as sessions.0.location.name.name. It should simply be sessions.0.location.name. We might wait to fix this until we switch to the handlebars helper for the dual-track sessions.

**Comment by kaymckelly** [comment]
Noted. This was something I've fixed in the past, but may have gotten lost when I had a merge conflict and was one that slipped through the cracks. Let's plan to keep this on the docket for fixing until we get that handlebars helper up and running.

**Comment by kaymckelly** [comment]
Checked and verified that this is no longer an issue.
