### ISSUE TITLE
Bad value alert for attribute role on element aside.

### ISSUE THREAD

**Issue by fabrice102** [kaymckelly/freelance-iacr#123]
In <https://github.com/kaymckelly/freelance-iacr/blob/master/www/travel.html#L98>, the W3 validator complains: Bad value alert for attribute role on element aside.

I am not exactly sure why it complains. Changing `<aside>` to `<div>` fixes the issue. But `<aside>` seems better suited.

**Comment by kaymckelly** [comment]
Weird, I'm not sure why it complains either. I agree that an <aside> seems better suited but I'll content myself with just having the alert role. Fwiw, I was working off http://html5doctor.com/downloads/h5d-sectioning-flowchart.png, which recommends using asides for pull quotes (i.e. closest thing I could liken this instance to).

Anyway, if you ever discover why the validator complains about this, let me know! I did some poking, but couldn't find anything.
