### ISSUE TITLE
Redundant stylesheet

### ISSUE THREAD

**Issue by fabrice102** [kaymckelly/freelance-iacr#124]
I think the stylesheet <https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css> should be removed, as <https://maxcdn.bootstrapcdn.com/bootswatch/3.3.7/spacelab/bootstrap.min.css> already contains it, if I'm not mistaken.

**Comment by kaymckelly** [comment]
Resolved with https://github.com/kaymckelly/freelance-iacr/commit/d0ae5566b32b781c29a8f063de507d642e5be5e6
