### ISSUE TITLE
Favicon

### ISSUE THREAD

**Issue by fabrice102** [kaymckelly/freelance-iacr#125]
Should we add the favicon <https://www.iacr.org/favicon.ico>?

The Crypto 2017 website <https://www.iacr.org/conferences/crypto2017> automatically has it thanks to its url. But the "new" conference websites (e.g., <https://crypto.iacr.org/2018> or <https://eurocrypt.iacr.org/2018>) don't have it, as there is no <https://crypto.iacr.org/favicon.ico> for example.

**Comment by rosulek** [comment]
That's a great idea. I have added favicons to all the CONFNAME.iacr.org sites.

**Comment by rosulek** [comment]
(issue can be closed but I don't see a way to do it)

**Comment by fabrice102** [comment]
I've closed it.
