### ISSUE TITLE
Search Engine Optimization (SEO)

### ISSUE THREAD

**Issue by fabrice102** [kaymckelly/freelance-iacr#126]
It seems that having empty titles and dynamic content for the conference names / dates might hurt SEO. Crypto 2018 website does not yet appear in Google's result for example.

But this might just be because it takes time to appear in the results. For example, this website <https://www.stephanboyer.com/post/122/does-google-execute-javascript> seems to indicate that Google sometimes does execute Javascript.

For Crypto 2018, I've manually hardcoded these values on Oct 23, using the following commands:

```
find . -name '*.html' -exec sed -i'.bak' 's/<title>/<title>Crypto 2018 - /' {} \;
find . -name '*.html' -exec sed -i'.bak' 's/<span class="conf_name"><\/span>/Crypto 2018/' {} \;
find . -name '*.html' -exec sed -i'.bak' 's/<span class="long_conf"><\/span>/Crypto 2018/' {} \;
find . -name '*.html' -exec sed -i'.bak' 's/<span class="conf_dates"><\/span>/August 19-23, 2018/' {} \;
find . -name '*.html' -exec sed -i'.bak' 's/<span class="conf_location"><\/span>/Santa Barbara, USA/' {} \;
```

and I've disabled the corresponding JavaScript. 

Crypto 2018 website seems to now appear correctly in Google search results but it might just be a coincidence. This might also be because I played a bit with "Google Search Console".

Furthermore, at least today (Oct. 25), the title in the search results is incorrect: it's "Crypto 2018 Crypto 2018" instead of "Crypto 2018". One explanation might be that Google still executed the old JavaScript scripts which prepend "Crypto 2018" to the title. But this does not explain why "Crypto 2017" title appears as "Crypto 2017 - International Association for Cryptologic Research" in the Google search results, while I cannot find this string anywhere in the Crypto 2017 website...

Interesting references:
- <https://static.googleusercontent.com/media/www.google.com/en//webmasters/docs/search-engine-optimization-starter-guide.pdf>
- <https://developers.google.com/search/docs/guides/>

**Comment by kmccurley** [comment]
I am constrained on what I can say here about search ranking, but I can confirm that javascript is irrelevant to ranking (almost all of the web is now based on javascript).  The currently indexed version seems to have "Crypto 2018 Crypto 2018" as the title, and the fact that the title has changed multiple times probably doesn't help, but eventually it will pick up the new version. The redirect of https://crypto.iacr.org/ is also probably a bad idea - I have no idea who added that but it probably degrades domain quality.

**Comment by rosulek** [comment]
I redirected crypto.iacr.org to something since I preferred some crypto-relevant information over a blank page. I had not considered "domain quality" related to SEO. But it sounds like you are saying google should have no problem indexing the JS-populated website correctly. So our lack of search visibility is unrelated to that.

One option we've discussed is a simple placeholder page as soon as the conference date/location is finalized. That might help get things indexed sooner.

**Comment by fabrice102** [comment]
We still have issue with SEO: the website does not appear in the first pages in many cases (for example, on my computer, with locales "French" and "English", it appears on the first page when searching for "Crypto 2018", but in incognito mode, it does not appear in the first page when searching for "Crypto 2018"; it seems to always appear on the first page when searching for "IACR Crypto 2018" though).

I think the title "Crypto 2018 Crypto 2018" comes from the fact that for maybe 10min, both the Javascript and the html tried to set up the `<title>` tag (actually I'm not even sure that I pushed such a version, maybe it is just that Google used a cached JS file). This is no more the case (everything is hardcoded) but this still appears as "Crypto 2018 Crypto 2018" on Google search, even after asking to re-index the pages using Google Search Console.

Thinking more about it, another reason of these issues with SEO might be that we shortened the text on the first page to

```
Crypto 2018 will take place in Santa Barbara, USA on August 19-23, 2018. 
It is organized by <a href="http://iacr.org/">the International Association for Cryptologic Research</a> (IACR).
```

instead of

```
Crypto 2017 is the 37th International Cryptology Conference. 
It will be held at the University of California, Santa Barbara (UCSB) August 20-24 2017. 
The academic program covers all aspects of cryptology. 
The conference is sponsored by the International Association for Cryptologic Research (IACR), in cooperation with the Computer Science Department of UCSB.
```

We have now slightly extended it. Do you think it might have indeed been an issue?

We've also move the text

```
New Affiliated events. Please visit the call for proposals to suggest an event. Deadline: January 10, 2018.
```

(which was before on top of the page) and put it in an `<aside>` tag.

We will see how things go.

**Comment by kmccurley** [comment]
This seems to be working reasonably well now (Asiacrypt points to the right site, 4 months before the conference).
