### ISSUE TITLE
Use of h1 in noscript

### ISSUE THREAD

**Issue by fabrice102** [kaymckelly/freelance-iacr#127]
The W3 validator recommends not using multiple `<h1>` tags:

`Consider using the h1 element as a top-level heading only (all h1 elements are treated as top-level headings by many screen readers and other tools).`

https://www.w3.org/wiki/HTML/Usage/Headings/h1only

Maybe the `<h1>` tag in `<noscript>` should be changed to `<h2>`.

**Comment by kaymckelly** [comment]
Addressed with https://github.com/kaymckelly/freelance-iacr/commit/d41d9b515a8caa9baf9ccf376f3b0cb934407715
