### ISSUE TITLE
Templating engine

### ISSUE THREAD

**Issue by kaymckelly** [kaymckelly/freelance-iacr#51]
Use mustache (possibly Handlebars?) instead of plain HTML5 to generate new pages and ultimately make the whole design more reusable for future conferences with this organization.

**Comment by rosulek** [comment]
I think this is a good idea, but if the goal is to make things easier for future conference organizations, then it's very easy to overestimate their capabilities. ;) If it requires doing fancy things like having a node.js installation, then they will probably not (be able to) do it. If all of this templating is built into the site on client-side, then I worry about compatibility. We could consider some server-side thing -- but only if it's simple. We try to minimize what's installed on the server.

**Comment by kmccurley** [comment]
It won't require node.js, and the amount of javascript is miniscule. My fear is that the CSS is a bigger problem than the javascript templates, so if someone wants to modify the schedule to contain three tracks, they are basically screwed.

**Comment by rosulek** [comment]
I see. I think IACR conferences with 3 tracks would be a really great problem to have. In this case, if it's just a one-time event where someone like me re-generates some CSS files for n=3, then I'm totally on board. If it's something every conf organizer has to do, then it's less ideal.

**Comment by kaymckelly** [comment]
Decided on Handlebars, in process of switching all necessary pages to that now.
